# Site settings

title: "Stephanie Liu"
email: stephofliu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Welcome to the personal website and blog of Stephanie Liu,
    a front-end developer at Magento.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ramenhog.com" # the base hostname & protocol for your site

# Build settings

markdown: kramdown
sass:
  sass_dir: _sass
permalink: /:categories/:title

# Plugins
whitelist: []
gems:      [jekyll-paginate, jekyll-seo-tag, jekyll-assets]

# Syntax Highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Post Excerpt
excerpt_separator: <!--more-->

# Permalink
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:categories/:title


# Social Links
twitter_username:     ramenhog
github_username:      ramenhog
linkedin_username:    ramenhog
codepen_username:     ramenhog

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

# SEO Settings
twitter:
  username: ramenhog
author: 
  twitter: ramenhog
defaults:
  - scope:
      path: ""
    values:
      image: /assets/ramenhog.jpg
social:
  name: Stephanie Liu
  links:
    - https://twitter.com/ramenhog
    - https://www.linkedin.com/in/ramenhog
    - https://github.com/ramenhog
    - http://codepen.io/ramenhog/
